#!/usr/bin/env bash
# _status_rollup.sh — scan .plan.md front-matter and emit STATUS.md
#
# Reads YAML front-matter (between two `---` fences) from every *.plan.md in
# this directory, extracts status/phase/prs/related_skills fields, and writes
# a STATUS.md table + Mermaid Gantt to the same directory.
#
# Status values recognized: not_started | in_progress | blocked | complete
# Plans with no `status:` field are listed under "unannotated".
#
# Run from anywhere; output always lands in the same directory as this script.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/STATUS.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Extract a single scalar key value from front-matter (between first two ---).
# Matches ONLY column-1 keys to avoid picking up nested status: lines inside
# todos: lists (which use 2-space indentation).
# Usage: get_field <file> <key>
get_field() {
  awk -v key="$2" '
    /^---$/ { c++; if (c == 2) exit; next }
    c == 1 && match($0, "^" key ":[ \t]*") {
      val = substr($0, RLENGTH + 1)
      gsub(/^"|"$/, "", val)
      print val
      exit
    }
  ' "$1"
}

# Extract a list-valued key from front-matter (YAML block-list of "- value").
# Usage: get_list <file> <key>
get_list() {
  awk -v key="$2" '
    /^---$/ { c++; if (c == 2) exit; next }
    c != 1 { next }
    match($0, "^" key ":[ \t]*$") { capture = 1; next }
    capture && /^  - / {
      sub(/^  - /, "")
      gsub(/^"|"$/, "")
      print
      next
    }
    capture && !/^  / { capture = 0 }
  ' "$1"
}

status_emoji() {
  case "$1" in
    complete)      echo "🟢" ;;
    in_progress)   echo "🟡" ;;
    blocked)       echo "🔴" ;;
    not_started)   echo "⚪" ;;
    *)             echo "❔" ;;
  esac
}

# ---------------------------------------------------------------------------
# Build rows
# ---------------------------------------------------------------------------

# Row format (tab-separated, sortable by phase): phase \t status \t name \t file \t prs \t related_skills
for f in "$DIR"/*.plan.md; do
  base="$(basename "$f")"
  name="$(get_field "$f" name)"
  [ -z "$name" ] && name="$base"
  status="$(get_field "$f" status)"
  phase="$(get_field "$f" phase)"
  prs="$(get_list "$f" prs | tr '\n' ',' | sed 's/,$//; s/,/, /g')"
  skills="$(get_list "$f" related_skills | tr '\n' ',' | sed 's/,$//; s/,/, /g')"
  # phase_key for sort: numeric phase if set, "99" otherwise so master/meta go last
  phase_key="${phase:-99}"
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$phase_key" "${status:-(none)}" "$name" "$base" "$prs" "$skills" >> "$TMP"
done

# ---------------------------------------------------------------------------
# Emit STATUS.md
# ---------------------------------------------------------------------------

{
  printf '# Plan Status Rollup\n\n'
  printf 'Generated by `_status_rollup.sh` at %s.\n\n' "$(date -u +'%Y-%m-%d %H:%M:%S UTC')"
  printf 'Source of truth: front-matter (`status:`, `phase:`, `prs:`, `related_skills:`) inside each `*.plan.md` in this directory.\n\n'

  # Summary tile counts
  total=0; comp=0; inprog=0; blk=0; ns=0; unann=0
  while IFS=$'\t' read -r _ status _ _ _ _; do
    total=$((total + 1))
    case "$status" in
      complete)    comp=$((comp + 1)) ;;
      in_progress) inprog=$((inprog + 1)) ;;
      blocked)     blk=$((blk + 1)) ;;
      not_started) ns=$((ns + 1)) ;;
      *)           unann=$((unann + 1)) ;;
    esac
  done < "$TMP"

  printf '## Summary\n\n'
  printf '| State | Count |\n|---|---|\n'
  printf '| 🟢 complete | %d |\n' "$comp"
  printf '| 🟡 in_progress | %d |\n' "$inprog"
  printf '| 🔴 blocked | %d |\n' "$blk"
  printf '| ⚪ not_started | %d |\n' "$ns"
  printf '| ❔ unannotated | %d |\n' "$unann"
  printf '| **Total** | **%d** |\n\n' "$total"

  # Plan table (sorted by phase_key, then by name)
  printf '## Plans\n\n'
  printf '| | Phase | Status | Name | File | PRs | Related skills |\n'
  printf '|---|---|---|---|---|---|---|\n'
  sort -k1,1n -k3,3 "$TMP" | while IFS=$'\t' read -r phase_key status name file prs skills; do
    emoji="$(status_emoji "$status")"
    display_phase="${phase_key/99/—}"
    printf '| %s | %s | `%s` | %s | `%s` | %s | %s |\n' \
      "$emoji" "$display_phase" "$status" "$name" "$file" "${prs:-—}" "${skills:-—}"
  done

  # Mermaid Gantt (only plans with phase 0-12)
  printf '\n## Phase Gantt (status snapshot)\n\n'
  printf '```mermaid\n'
  printf 'gantt\n'
  printf '    title Notification rules + semantic email — phase status\n'
  printf '    dateFormat  YYYY-MM-DD\n'
  printf '    axisFormat  P%%s\n'
  printf '    section Phases\n'
  sort -k1,1n "$TMP" | while IFS=$'\t' read -r phase_key status name _ _ _; do
    [[ "$phase_key" == "99" ]] && continue
    case "$status" in
      complete)    tag="done," ;;
      in_progress) tag="active," ;;
      blocked)     tag="crit," ;;
      *)           tag="" ;;
    esac
    # Gantt requires placeholder dates; use phase number to anchor a 1-day band
    start_day=$(printf '2026-01-%02d' $((phase_key + 1)))
    printf '    Phase %s — %s : %sp%s, %s, 1d\n' "$phase_key" "$status" "$tag" "$phase_key" "$start_day"
  done
  printf '```\n\n'

  printf '## Regenerate\n\n'
  printf '```bash\n'
  printf 'bash %s/_status_rollup.sh\n' "$(dirname "$OUT")"
  printf '```\n'
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
